#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_System */

#ifndef _Included_string_md
#define _Included_string_md
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jbyteArray JNICALL Java_java_lang_StringCoding_encode
  (JNIEnv *, jclass, jcharArray, jint, jint);

JNIEXPORT jcharArray JNICALL Java_java_lang_StringCoding_decode
	(JNIEnv *, jclass, jbyteArray, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
